apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo
      version: "1.7.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    tempo:
      storage:
        trace:
          backend: local
      receiver:
        otlp:
          protocols:
            grpc:
              enabled: true
              endpoint: "0.0.0.0:4317"
            http:
              enabled: true
              endpoint: "0.0.0.0:4318"
