apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
type: Opaque
stringData:
  admin-user: admin
  admin-password: Q2FjdHVzLmdhbWluZy5uZXQuc3RyaXAubmV0