apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: observability-stack
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/usuario/observability-stack.git
  branch: main