apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: observability
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: strongpassword123

