apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.69.0"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  values:
    mode: deployment

    config:
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}
      
      
      exporters:
        otlp:
          endpoint: tempo:4317
          tls:
            insecure: true
        logging: {}  # Exporter para depuração/logs locais

      service:
        pipelines:
          traces:
            receivers: [otlp]
            exporters: [otlp, logging]  # Logging para debug
          logs:
            receivers: [otlp]
            exporters: [logging]
          metrics:
            receivers: [otlp]
            #exporters: [prometheus]  # Descomente se desejar expor métricas para Prometheus
