apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.69.0"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  values:
    mode: deployment
    config:
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}
      exporters:
        otlp:
          endpoint: tempo:4317
          tls:
            insecure: true
        #prometheus:
        #  endpoint: prometheus-server
        logging: {}  # Exporter usado na pipeline de logs
      service:
        pipelines:
          logs:
            receivers: [otlp]
            exporters: [logging]
          traces:
            receivers: [otlp]
            exporters: [otlp]  # Corrigido: exportando para o Tempo via OTLP
          metrics:
            receivers: [otlp]
            #exporters: [prometheus]
