apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
      version: 0.78.0
  values:
    mode: deployment
    config:
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}
      processors:
        batch: {}
      exporters:
        otlp:
          endpoint: tempo.observability.svc.cluster.local:4317
          tls:
            insecure: true
        prometheus:
          endpoint: "0.0.0.0:8889"
        loki:
          endpoint: http://loki.observability.svc.cluster.local:3100/loki/api/v1
          labels:
            attributes:
              container: container.name
              namespace: k8s.namespace.name
              pod: k8s.pod.name
        logging:
          loglevel: debug
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp, logging]
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheus, logging]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [loki, logging]
