apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "5.44.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    persistence:
      enabled: false
      size: 50Gi
      storageClassName: gp2
    service:
      type: ClusterIP
      port: 3000
      targetPort: 3000
    ingress:
      enabled: false
    config:
      table_manager:
        retention_deletes_enabled: true
        retention_period: 168h  # 7 dias de retenção de logs

